apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_URI: >-
    mongodb://admin:password@mongodb-0.mongodb.todo.svc.cluster.local:27017,
    mongodb-1.mongodb.todo.svc.cluster.local:27017,
    mongodb-2.mongodb.todo.svc.cluster.local:27017/?replicaSet=rs0&authSource=admin
