version: '3.8'

services:
  # Frontend Service (Vite + React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-react-app
    expose:
      - "5173"  # Only expose to Docker network (not host)
    environment:
      - VITE_BACKEND_URL=/api  # All API calls will go through Nginx
    networks:
      - app-network

  # Backend Service (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-app
    expose:
      - "5000"  # Only expose to Docker network
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PORT=5000
      - JWT_SECRET=thisisjwtsecretthisisjwtsecretthisisjwtsecretthisisjwtsecret
      - FRONTEND_URL=52.66.5.154
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # For HTTPS (optional)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # For HTTPS certs (optional)
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  # MongoDB (unchanged)
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
