apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: todo
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:6.0
          command: ["sh", "-c"]
          args:
            - |
              sleep 10;
              mongo --host mongodb-0.mongodb:27017 \
              -u admin -p password --authenticationDatabase admin <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongodb-0.mongodb:27017" },
                  { _id: 1, host: "mongodb-1.mongodb:27017" },
                  { _id: 2, host: "mongodb-2.mongodb:27017" }
                ]
              });
              EOF
      restartPolicy: OnFailure
      backoffLimit: 4
