# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or "master" or any branch you prefer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
