# .github/workflows/build-backend.yml
name: Build and Push Backend Image

on:
  push:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest ./backend

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
