# .github/workflows/build-frontend.yml
name: Build and Push Frontend Image

on:
  push:
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest ./frontend

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
